### ISSUE TITLE
Makefile for Large Project

### ISSUE THREAD

**Issue by carismoses** [jlopezvi/Flowgen#6]
Hi,

I am interested in using Flowgen for a very large project. Do you have another example of a Makefile I could use as a reference? One which has more than 1 file in the source directory, and is not a subdirectory of /Flowgen? It would be very useful.

Best,
Caris

**Comment by jlopezvi** [comment]
Dear Caris,

Maybe the makefile in this project VINCIA can give you some inspiration, look for the references of Flowgen.
https://www.dropbox.com/s/bz7n7s1bg8p31wi/vincia-trunk.zip?dl=0
Unfortunately, I can no longer make run the project, so that it is impossible to refresh the Flowgen documentation. But, as I say, you can use the makefile perhaps as inspiration.

If you have something to share for other users about your experience it will be welcomed.

**Comment by carismoses** [comment]
Thank you @jlopezvi . I just got the /EXAMPLES project to `make` so now I will work on using a larger project based on the files you provided.

**Comment by carismoses** [comment]
Actually I do have a quick question for you. Is there a reason you made your own cindex.py as opposed to using the one provided by the llvm+clang tools? Just trying to watch out for any potentially issues I may have with flowgen going forward.

**Comment by jlopezvi** [comment]
we work with python3 and at the time clang did not supported it. 
As far as I understand, clang is already working with python3 bindings or should work in the near future with it.
Me or someone else should update the project to use the official clang bindings

**Comment by carismoses** [comment]
Hey @jlopezvi . When I run my code with the build_db.py code I am not getting anything in the .flowdb output in /aux_files. I am looking at the build_db.py code and I was hoping you would be able to tell me what regular expressions your code is looking for when it writes to the .flowdb file?

More specifically, what is it trying to match from the source code with this line?
`regextextActionComment=r'^\s*//\$'+str(zoom)+r'(?!\s+\[)\s+(?P<action>.+)$'`

**Comment by carismoses** [comment]
Disregard that. I will start a new issue for my question.
